### ISSUE TITLE
Multiple hosts for one service do not work 

### ISSUE THREAD

**Issue by bborbe** [albertrdixon/romulus#32]
I try set two hostnames for the same service but only one of them works. I guess the problem is they use the same id "example.example.web".

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    romulus/lb: vulcan
    romulus/route: public
  name: example
  namespace: example
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: web
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: example
          servicePort: web
```

```
[romulusd] 2016/04/29 20:02:42 [info] Upserting HTTPServer(example.example.df7503ec, http://10.102.88.31:80, <nil>)
[romulusd] 2016/04/29 20:02:42 [info] Upserting Frontend(http, example.example.web, example.example.web)
[romulusd] 2016/04/29 20:02:42 [info] Upserting Frontend(http, example.example.web, example.example.web)
```

```
/vulcand/backends
/vulcand/backends/example.example.web
/vulcand/backends/example.example.web/backend
/vulcand/backends/example.example.web/servers
/vulcand/backends/example.example.web/servers/example.example.df7503ec
/vulcand/frontends
/vulcand/frontends/example.example.web
/vulcand/frontends/example.example.web/frontend
```

`{"Id":"example.example.web","Route":"Host('www.example.com')","Type":"http","BackendId":"example.example.web","Settings":{"Limits":{"MaxMemBodyBytes":1048576,"MaxBodyBytes":1048576,"MaxRespMemBodyBytes":1048576,"MaxRespBodyBytes":1048576},"FailoverPredicate":"","Hostname":"www.example.com","TrustForwardHeader":true,"PassHostHeader":true}}`
